### ISSUE TITLE
Parsec fails when using it from an installed package

### ISSUE THREAD

**Issue by keroami** [cute-jumper/parsec.el#3] opened 2017-04-26 11:09 UTC
Hi!

I get (invalid-function parsec-and) from parsec-try.
Got it down to the fact that code gets compiled, but there's more to be uncovered, I think.
The attached file demonstrates the problem.
I can convert it to an ert test if you want me to, although there will be an additional function.

For the moment I work around the packaging problem by adding
`;; -*-no-byte-compile: t; -*-`
to the file doing the parsing.

[dpcp.txt](https://github.com/cute-jumper/parsec.el/files/958133/dpcp.txt)

Bye,
Kero.

**Comment by cute-jumper** [comment] 2017-04-26 17:10
Hmm, I can't reproduce the problem using `emacs -Q` on Emacs 25.2. Here is what I did:

Start emacs with `emacs -Q`, then `package-initialize`. In scratch buffer, paste the following code:
```
(require 'parsec)

(defun parse-buffer ()
  (save-excursion
    (goto-char (point-min))
    (parsec-parse (parse-comment))))

(defun parse-comment ()
  `(comment-prefix
    ,(parsec-try
      (parsec-string ";;;"))))
```

Then:
```
M-: (eval-buffer)
M-: (parse-buffer)
M-: (byte-compile 'parse-comment)
M-: (parse-buffer)
```

Seems to work correctly. Can you give me more details to reproduce the problem?

**Comment by keroami** [comment] 2017-04-27 17:28
You *do* have ';;;' at the start of the buffer, right? parsec-string has to match.
Otherwise parsec gives the correct parsing error in both byte compiled and interpreted.

I made a few more attempts, anyway, but I have the problem with all attempts I made:
 - using `emacs -Q` for all other attempts.
 - tried it on debian 32 bits system
 - tried parsec 0.1.3 as well as 20170219.1442 from melpa. Can't tell whether that is current master, but made an install from git master, regardless.
 - only distros I have readily available (debian unstable, Ubuntu 16.04 and a Linux Mint) all use Debian base package 24.5.1.
 - installed emacs 25.2 on Ubuntu 16.04, from gnu itself, compiled by hand.

stacktrace looks like this (25.2 omits the lines with bytecode)
```Debugger entered--Lisp error: (invalid-function parsec-and)
  parsec-and(";;;")
  byte-code("\300\301\302\303\304\305\"\262!\"\207" [throw parsec-failed-eavesdrop-error parsec-and ";;;" mapc #[257 "\300!\207" [parsec-ch] 3 "\n\n(fn C)"]] 7)
  byte-code("\302\303\215	b\210\304\302\"\262)\207" [err orig-pt parsec-failed (byte-code "\300\301\302\303\304\305\"\262!\"\207" [throw parsec-failed-eavesdrop-error parsec-and ";;;" mapc #[257 "\300!\207" [parsec-ch] 3 "\n\n(fn C)"]] 7) throw] 4)
  parse-comment()
  (catch (quote parsec-failed) (parse-comment))
  (save-excursion (goto-char (point-min)) (catch (quote parsec-failed) (parse-comment)))
  parse-buffer()
  eval((parse-buffer) nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)```

I can try more variations (other linux (live) distros, windows), but they take more effort from my side. Will do, if necessary.

**Comment by cute-jumper** [comment] 2017-04-27 19:07
> You do have ';;;' at the start of the buffer, right?

Sorry about that. I overlooked that part. My bad.

I see the problem now. It's not `parsec` specific, but is related to byte-compiling `defalias` and special forms. See the minimal example:

```
(defalias 'new-progn 'progn)
(defun foo ()
  (new-progn "foo"))
(byte-compile 'foo)
(foo) 
```

This gives "Invalid function: new-progn". It seems like the problem is caused by defining an alias for the special form `progn`. Replacing `progn` with other non-special-form functions will not get the error. Don't know why. I may ask this on emacs.stackexchange.com later.

Redefining `parsec-and` using normal `defmacro` should fix the problem.

Thanks for reporting this problem!

EDIT: Look like only `progn`, `prog1`, `prog2` have this problem. Other special forms like `and`, `or` work OK.

**Comment by keroami** [comment] 2017-04-29 14:57
A subtle problem, I'd say.
Your minimal example triggers it for me, too.
Not entirely sure how to write that macro... `progn` is indeed a special form.
If `prog1` has the same behaviour, `parsec-return` probably has the same problem (but I have not used that function, yet).

Thanks for your quick reactions!

**Comment by cute-jumper** [comment] 2017-05-08 20:05
Waited for over one week and my stackexchange problem seems still unanswered. I'll just apply the simple fix in #4. Could #4 also fix the problem for you?

**Comment by keroami** [comment] 2017-05-08 21:58
Yes, it does. Thanks!

**Comment by cute-jumper** [comment] 2017-05-08 22:00
Cool. Merged.

**Closed as completed** 2017-05-08 22:00 UTC
